### ISSUE TITLE
Doesn’t show up in Home app

### ISSUE THREAD

**Issue by d0n4v4nb3ck3r** [g30r93g/homebridge-ring-doorbell#1]
When I install this plugin on my HomeBridge, it doesn’t bring anything up in the Apple home app

**Comment by jahnkenneth** [comment]
Same here... :-(

**Comment by dVIAN13** [comment]
having issue as well. It appears the plugin silently fails... logs show last entry 'didFinishLaunching', however, no Device ID's are captured.

**Comment by jahnkenneth** [comment]
@g30r93g Any updates coming soon? :-)

**Comment by g30r93g** [comment]
Hi sorry for the delayed response. I've been trying to balance studying A Levels with this plugin and my other Panasonic TV plugin, so I'm sorry I haven't been on top of things. However, now that the Panasonic TV plugin is working pretty well, I'll start turning my attention towards this plugin. Currently, I've got it to show in the Home app but it's having a bit of an issue when trying to deal with caching and  then it crashes Homebridge and you end up needing to remove the persist and accessory folders. Nightmare. But hopefully you'll be seeing the doorbell in your home app soon. I do want to let you know that the Home app will show this accessory as 'Not Supported', though you will be able to receive notifications in the Home app and setup automations in 3rd party apps such as the Eve app.

**Comment by jahnkenneth** [comment]
Why will it show as not supported in the Home app? Does iOS 12.2 not support doorbells?
